name: Build orch
on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.os }} (lua${{ matrix.lua }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-latest]
        lua: [5.3, 5.4]
        include:
          - os: ubuntu-20.04
          - os: ubuntu-22.04
          - os: macos-latest
            lua: 5.4
            pkgs: cmake coreutils lua@5.4
        exclude:
          - os: ubuntu-20.04
            lua: 5.4
          - os: macos-latest
            lua: 5.3
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install system packages (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update --quiet || true
          sudo apt-get -yq --no-install-suggests --no-install-recommends install cmake liblua${{ matrix.lua }}-dev
      - name: install system packages (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update --quiet || true
          brew install ${{ matrix.pkgs }}
      - name: configure
        run: |
          mkdir build
          cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..
      - name: build orch(1)
        run: make -C build
      - name: Run self-tests
        run: make -C build check
