name: Lint orch.lua
on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions:
  contents: read

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install system packages
        run: |
          sudo apt-get update --quiet || true
          sudo apt-get -yq --no-install-suggests --no-install-recommends install cmake luarocks
      - name: install lua packages
        run: sudo luarocks install luacheck
      - name: configure
        run: |
          mkdir build
          cd build && cmake ..
      - name: run linter
        run: make -C build lint
